// src/pages/Home.svelte
<script lang="ts">
    import { createMutation, createQuery } from "@tanstack/svelte-query";
    import Page from "../components/Page.svelte";
    import Link from "../components/routing/Link.svelte";
    import { API } from "../utils/api";
    import type { Canvas } from "../types/canvas";
    import Tank from "../components/Tank.svelte";
    import { storage } from "../store";
    import { onMount } from "svelte";
    import Drawer from "../components/Drawer.svelte";

    const canvasQuery = createQuery({
        queryKey: ["canvas"],
        queryFn: () => API.canvases.list(),
    });

    const createCanvasMutation = createMutation({
        mutationFn: async () => await API.canvases.create(newCanvas),
        onSuccess: (data) => {
            $canvasQuery.refetch();
        },
    });

    let canvases: Canvas[] | undefined;
    let newCanvas: Partial<Canvas> = {
        name: "",
        inflow: 0,
        inflow_rate: "0 0 1 * *",
    };

    let drawerOpen: boolean = false;

    $: canvases = $canvasQuery.data?.results;
    $: console.log(canvases);

    let currentCanvasId: string | undefined;

    $: storage.set({
        ...$storage,
        currentCanvasId,
    });

    let currentCanvas: Canvas | undefined;

    $: currentCanvas = canvases?.find((c) => c.external_id === currentCanvasId);

    $: !$storage?.currentCanvasId &&
        storage.set({
            ...$storage,
            currentCanvasId: canvases?.[0]?.external_id,
        });

    const handleFormSubmit = (e: Event) => {
        e.preventDefault();
        $createCanvasMutation.mutate();
    };

    const baseCronOptions = [
        {
            value: "0 0 * * *",
            label: "Every day",
        },
        {
            value: "0 0 * * 0",
            label: "Every week",
        },
        {
            value: "0 0 1 * *",
            label: "Every month",
        },
        {
            value: "0 0 1 1 *",
            label: "Every year",
        },
    ];

    onMount(() => {
        currentCanvasId =
            $storage?.currentCanvasId || canvases?.[0]?.external_id;
    });
</script>

<div class="h-full flex flex-col">
    <div class="p-4">
        {#if canvases && canvases.length > 0}
            <select
                class="p-3 rounded-lg border bg-gray-900 border-gray-800 text-white w-full block"
                bind:value={currentCanvasId}
            >
                {#each canvases as canvas}
                    <option value={canvas.external_id}>{canvas.name}</option>
                {/each}
            </select>
        {/if}
    </div>
    <div class="flex-1">
        {#if canvases && canvases.length === 0}
            <div class="p-4">
                <h1 class="text-4xl font-extrabold">
                    Hey! Welcome to Dhanriti. Let's get started by creating a
                    canvas
                </h1>
                <br />
                <form on:submit={handleFormSubmit}>
                    <input
                        bind:value={newCanvas.name}
                        type="text"
                        placeholder="Canvas Name"
                        class="p-3 rounded-lg border bg-gray-900 border-gray-800 text-white w-full block mb-4"
                    />
                    Inflow:
                    <div class="flex items-center gap-4">
                        <div class="flex items-center gap-2">
                            <input
                                bind:value={newCanvas.inflow}
                                type="number"
                                placeholder="Inflow Amount"
                                class="p-3 rounded-lg border bg-gray-900 border-gray-800 text-white w-full mt-4 block"
                            />
                            <div>Rs.</div>
                        </div>
                        <select
                            bind:value={newCanvas.inflow_rate}
                            class="p-3 rounded-lg border bg-gray-900 border-gray-800 text-white w-full mt-4 block"
                        >
                            {#each baseCronOptions as op}
                                <option value={op.value}>
                                    {op.label}
                                </option>
                            {/each}
                        </select>
                    </div>
                    <button
                        class="bg-yellow-500 text-black p-3 rounded-lg mt-4 w-full font-extrabold ripple"
                        disabled={$createCanvasMutation.isPending}
                    >
                        Create
                    </button>
                </form>
            </div>
        {/if}
        {#if canvases && canvases.length > 0}
            <div class="w-screen h-full overflow-auto">
                <div
                    class="bg-gray-900 relative flex flex-col items-center dhanriti-canvas min-w-full min-h-full"
                >
                    <div
                        class="bg-gray-800 w-[130px] h-[30px] flex items-center justify-center text-gray-500 font-extrabold"
                    >
                        <i class="far fa-arrow-down" />
                        &nbsp; Inflow &nbsp;
                        <i class="far fa-arrow-down" />
                    </div>
                    <Tank
                        tank={{
                            name: "Main Tank",
                            filled: 200,
                        }}
                        class=" w-[200px] h-[100px] mt-5"
                    />
                    <button
                        class="fixed bottom-20 right-10 w-14 h-14 bg-yellow-500 flex items-center justify-center rounded-full shadow-xl text-2xl text-black"
                        on:click={() => {
                            drawerOpen = true;
                        }}
                    >
                        <i class="fas fa-plus" />
                    </button>
                </div>
                <Drawer
                    open={drawerOpen}
                    onClose={() => {
                        drawerOpen = false;
                    }}
                    menu={[
                        {
                            name: "New Tank",
                            icon: "tank-water",
                            onClick: () => {
                                drawerOpen = false;
                            },
                        },
                        {
                            name: "New Funnel",
                            icon: "funnel-dollar",
                            onClick: () => {
                                drawerOpen = false;
                            },
                        },
                    ]}
                />
            </div>
        {/if}
    </div>
</div>

// src/pages/Home.tsx
import { useTranslation } from "react-i18next";
import {
    Button,
    Drawer,
    FallBack,
    IconButton,
    Menu,
    Select,
    WarningDrawer,
    raviger,
} from "@kacker/ui";
import { useAtom } from "jotai";
import { storageAtom } from "../store";
import { useMutation, useQuery } from "@tanstack/react-query";
import { API } from "../utils/api";
import { Canvas } from "../types/canvas";
import CanvasBlock from "../components/Canvas";
import { useEffect, useState } from "react";
import CanvasForm from "../components/forms/CanvasForm";
import Loading from "../components/loading";

export default function HomePage() {
    const { t } = useTranslation();

    const [storage, setStorage] = useAtom(storageAtom);
    const [editCanvasDrawerOpen, setEditCanvasDrawerOpen] = useState(false);
    const [deleteCanvasDrawerOpen, setDeleteCanvasDrawerOpen] = useState(false);
    const [createCanvasDrawerOpen, setCreateCanvasDrawerOpen] = useState(false);

    const handleRefresh = async () => {
        if (canvasQuery.isFetching) return;
        await Promise.all([canvasQuery.refetch()]);
    };

    const canvasQuery = useQuery(["canvases"], () => API.canvases.list(), {
        enabled: !!storage?.auth_token,
    });
    const canvases: Canvas[] | undefined = canvasQuery.data?.results;
    const selectedCanvas = canvases?.find(
        (canvas) => canvas.external_id === storage?.selectedCanvasId
    );

    const canvasUpdateMutation = useMutation(
        ({ canvas }: { canvas: Partial<Canvas> }) =>
            API.canvases.save(canvas.external_id || "", canvas),
        {
            onSuccess: (data) => {
                canvasQuery.refetch();
                setStorage({ ...storage, selectedCanvasId: data.external_id });
            },
        }
    );

    const canvasCreateMutation = useMutation(
        ({ canvas }: { canvas: Partial<Canvas> }) =>
            API.canvases.create(canvas),
        {
            onSuccess: () => {
                canvasQuery.refetch();
            },
        }
    );

    const deleteCanvasMutation = useMutation(
        ({ canvasId }: { canvasId: string }) =>
            API.canvases.delete(canvasId || ""),
        {
            onSuccess: () => {
                canvasQuery.refetch();
            },
        }
    );

    useEffect(() => {
        if (
            canvases &&
            storage?.auth_token &&
            canvases.length > 0 &&
            (!storage?.selectedCanvasId ||
                !canvases.find(
                    (canvas) => canvas.external_id === storage?.selectedCanvasId
                ))
        ) {
            setStorage({
                ...storage,
                selectedCanvasId: canvases[0].external_id,
            });
        }
    }, [canvases, storage?.auth_token]);

    return (
        <div className="h-screen flex flex-col justify-between pt-[calc(var(--status-bar-height,0))]">
            {canvasQuery.isLoading && <Loading />}
            {canvases && canvases.length > 0 && (
                <div className="p-2 flex gap-2 justify-between items-center">
                    <Select
                        title={t("select_canvas")}
                        value={storage?.selectedCanvasId || ""}
                        onChange={(value) =>
                            setStorage({
                                ...storage,
                                selectedCanvasId: value || "",
                            })
                        }
                        options={
                            canvases?.map((canvas) => ({
                                label: canvas.name,
                                value: canvas.external_id,
                            })) || []
                        }
                        className="w-full"
                    />
                    <IconButton
                        className="shrink-0"
                        icon="circle-plus"
                        onClick={() => setCreateCanvasDrawerOpen(true)}
                    />
                    {storage?.selectedCanvasId && (
                        <Menu
                            menu={[
                                {
                                    label: "Edit Canvas",
                                    onClick: () => {
                                        setEditCanvasDrawerOpen(true);
                                    },
                                    icon: "pen",
                                },
                                {
                                    label: "Flow Records",
                                    onClick: () => {
                                        raviger.navigate(
                                            "/flows?canvas=" +
                                                storage?.selectedCanvasId
                                        );
                                    },
                                    icon: "chart-line",
                                },
                                {
                                    label: "Delete Canvas",
                                    onClick: () => {
                                        setDeleteCanvasDrawerOpen(true);
                                    },
                                    icon: "trash",
                                    dangerous: true,
                                },
                            ]}
                        >
                            <IconButton
                                className="shrink-0"
                                icon="ellipsis-vertical"
                            />
                        </Menu>
                    )}
                </div>
            )}
            {canvases && canvases.length === 0 && (
                <div className="h-full flex items-center justify-center">
                    <div className="text-center p-4">
                        <div className="text-8xl">💸</div>
                        <br />
                        <h1 className="text-3xl font-extrabold">
                            {t("welcome")}!
                        </h1>
                        <br />
                        <p>
                            Dhanriti, as the name suggests is a tool to help you
                            plan your finances. Let&apos;s get started by
                            creating a canvas.
                        </p>
                        <br />
                        <br />
                        <Button
                            onClick={() => setCreateCanvasDrawerOpen(true)}
                            className="w-full"
                        >
                            Create Canvas
                        </Button>
                    </div>
                </div>
            )}
            <div className="flex-1 flex flex-col relative">
                {selectedCanvas ? (
                    <FallBack loading={canvasQuery.isLoading}>
                        <div className="flex-1 overflow-auto">
                            <CanvasBlock
                                canvas={selectedCanvas}
                                handleRefresh={handleRefresh}
                            />
                        </div>
                        <div className="absolute bottom-20 z-10 inset-x-0 pb-[var(--safe-area-inset-bottom)]">
                            <div className="text-center text-gray-500 text-sm">
                                Total
                            </div>
                            <div className=" text-center text-2xl font-extrabold">
                                <i className="far fa-indian-rupee-sign text-xl" />{" "}
                                {(
                                    Math.round(
                                        (selectedCanvas.total_money || 0) * 100
                                    ) / 100
                                ).toLocaleString("en-IN")}
                            </div>
                        </div>
                    </FallBack>
                ) : (
                    <div></div>
                )}
            </div>
            <Drawer
                open={editCanvasDrawerOpen}
                onClose={() => setEditCanvasDrawerOpen(false)}
                title="Edit Canvas"
            >
                <CanvasForm
                    canvas={selectedCanvas}
                    onSubmit={async (canvas) => {
                        await canvasUpdateMutation.mutateAsync({ canvas });
                        setEditCanvasDrawerOpen(false);
                    }}
                    submitLoading={canvasUpdateMutation.isLoading}
                />
            </Drawer>
            <Drawer
                open={createCanvasDrawerOpen}
                onClose={() => setCreateCanvasDrawerOpen(false)}
                title="Create Canvas"
            >
                <CanvasForm
                    onSubmit={async (canvas) => {
                        await canvasCreateMutation.mutateAsync({ canvas });
                        setCreateCanvasDrawerOpen(false);
                    }}
                    submitLoading={canvasCreateMutation.isLoading}
                />
            </Drawer>
            <WarningDrawer
                open={deleteCanvasDrawerOpen}
                title="Delete Canvas"
                content="Are you sure you want to delete this canvas? This action is irreversible."
                onConfirm={() => {
                    deleteCanvasMutation.mutate({
                        canvasId: selectedCanvas?.external_id || "",
                    });
                    setDeleteCanvasDrawerOpen(false);
                }}
                onCancel={() => setDeleteCanvasDrawerOpen(false)}
            />
        </div>
    );
}
