// src/pages/Login.svelte
<script>
    import Page from "../components/Page.svelte";
    import Link from "../components/routing/Link.svelte";
    import { createMutation } from "@tanstack/svelte-query";
    import { API } from "../utils/api";
    import { Capacitor } from "@capacitor/core";

    const serviceTokenMutation = createMutation({
        mutationFn: async () =>
            await API.user.login({
                client_url: Capacitor.isNativePlatform()
                    ? "dhanriti://dhanriti.shivank.dev"
                    : window.location.origin,
            }),
        onSuccess: (data) => {
            //window.open(data.url, "_blank");
            window.location.href = data.url;
        },
    });
</script>

<Page>
    <div class="flex items-center justify-center h-full">
        <div>
            <h1 class="font-extrabold text-5xl">Welcome to Dhanriti</h1>
            <br />
            <p>Login with your Kacker account to get started.</p>
            <br />
            <button
                class="flex items-center justify-between gap-4 bg-purple-600/20 rounded-lg p-4 text-purple-500 ripple"
                on:click={() => $serviceTokenMutation.mutate()}
            >
                <div class="flex items-center gap-4">
                    <img
                        src="https://auth.writeroo.net/kacker_w.svg"
                        class="w-6"
                        alt="Kacker"
                    />
                    Login with Kacker
                </div>
                <div>
                    {#if $serviceTokenMutation.isPending}
                        <i class="fas fa-spinner fa-spin" />
                    {:else}
                        <i class="far fa-arrow-right-long" />
                    {/if}
                </div>
            </button>
        </div>
    </div>
</Page>

// src/pages/Login.tsx
import { useMutation } from "@tanstack/react-query";
import { t } from "i18next";
import { Link, navigate, useQueryParams } from "raviger";
import { useEffect } from "react";
import { API } from "../utils/api";
import { storageAtom } from "../store";
import { useAtom } from "jotai";
import { Capacitor } from "@capacitor/core";
import { LoginWithKacker, RawPage } from "@kacker/ui";

export default function Login() {
    const [storage, setStorage] = useAtom(storageAtom);

    const serviceTokenMutation = useMutation(
        async () =>
            await API.user.login({
                client_url: Capacitor.isNativePlatform()
                    ? "dhanriti://dhanriti.shivank.dev"
                    : window.location.origin,
            }),
        {
            onSuccess: (data) => {
                //window.open(data.url, "_blank");
                window.location.href = data.url;
            },
        }
    );

    useEffect(() => {
        if (storage?.auth_token) {
            navigate("/", { replace: true });
        }
    }, [storage]);

    const onLogin = async () => {
        serviceTokenMutation.mutate();
    };
    return (
        <RawPage>
            <div className="flex justify-end flex-col h-full p-8 gap-10">
                <div>
                    <img
                        src={`/logo_full_${
                            document.documentElement.style.getPropertyValue(
                                "--kui-theme-type"
                            ) === "dark"
                                ? "white"
                                : "black"
                        }.svg`}
                        className="h-16"
                        alt="Logo"
                    />
                </div>
                <div className="font-extrabold text-5xl leading-[1.1]">
                    {t("login_title")}
                </div>
                <div className="text-gray-500">{t("login_description")}</div>
                <div className="w-full">
                    <LoginWithKacker
                        className="w-full"
                        loading={serviceTokenMutation.isLoading}
                        onClick={onLogin}
                    />
                </div>
            </div>
            <div className="absolute -bottom-10 -inset-x-10 h-[70%] bg-gradient-to-t from-accent-400 to-transparent gradient-pulsate blur-lg hidden" />
        </RawPage>
    );
}

export function VishnuLogin() {
    const [storage, setStorage] = useAtom(storageAtom);
    const [{ success = false, token = null }] = useQueryParams();
    const loginMutation = useMutation(
        async () => await API.user.login({ login_token: token }),
        {
            onSuccess: (data) => {
                setStorage({
                    auth_token: data.token,
                    user: data.user,
                });
                navigate("/login", { replace: true });
            },
        }
    );

    useEffect(() => {
        if (success) {
            getToken();
        }
    }, []);

    const getToken = async () => {
        await loginMutation.mutateAsync();
    };

    return (
        <RawPage>
            {loginMutation.isError || !token ? (
                <div className="text-center">
                    There was an error logging in.
                    <br />
                    <br />
                    <Link href="/login" className="text-purple-500">
                        Try Again
                    </Link>
                </div>
            ) : (
                <div>Logging in...</div>
            )}
        </RawPage>
    );
}
